site_name: Aegear
site_url: https://ljubobratovicrelja.github.io/aegear/
repo_url: https://github.com/ljubobratovicrelja/aegear
theme:
  name: material
  logo: media/logo_small.png
  favicon: media/logo_favicon.png
  features:
    - content.code.copy
    - content.code.annotate
nav:
  - Home: index.md
  - Installation: installation.md
  - Usage: usage.md
  - Calibration: calibration.md
  - Training: training.md
  - Docker: docker.md
  - Tutorial (API): tutorial_api.md
  - API: api.md
plugins:
  - search
  - mkdocstrings
markdown_extensions:
  - codehilite
  - pymdownx.highlight
  - pymdownx.superfences
